### ISSUE TITLE
Avatar component not working

### ISSUE THREAD

**Issue by mauthi** [enso-ui/users#1]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I tried to use the Avatar component in my application.

My component:
```
<template>
    <avatar class="is-24x24"
        :user="user"/>
</template>

<script>

import Avatar from '@enso-ui/users';

export default {
    components: {
        Avatar,
    },

    data: () => ({
        user: {
            avatar: {
                id: 1,
            },
        },
    }),
};

</script>
```

### Steps to Reproduce

1. Create a new component with source above
2. Use component in your application

### Expected behavior

Avatar should be shown

### Actual behavior

No avatar is shown.

Error:
![image](https://user-images.githubusercontent.com/7204559/99145526-03fc6f80-2670-11eb-94d8-495044652a6c.png)

- looks like it tries to call the initTable route? I guess the wrong component is used and the import doesn't work 

Possible problemens:
- missing index.js in users package to import and export the component? (I tried to add this but no success)
- if I copy the Avatar.vue to my project and import it from there everything works like expected

**Comment by raftx24** [comment]
Hi @mauthi 
the right way for importing `Avatar` is similar to [this](https://github.com/enso-ui/tasks/blob/master/src/bulma/pages/tasks/Index.vue#L127)
```
import VueSwitch from '@enso-ui/switch/bulma';
import { EnsoDatepicker } from '@enso-ui/datepicker/bulma';
import Avatar from '@enso-ui/users/src/bulma/pages/users/components/Avatar.vue';
import { faClock, faInfoCircle, faCog } from '@fortawesome/free-solid-svg-icons';
import { library } from '@fortawesome/fontawesome-svg-core';
import { VTooltip, VPopover } from 'v-tooltip';
```

**Comment by raftx24** [comment]
I also created this [PR](https://github.com/enso-ui/users/pull/2) for easier usage!

**Comment by mauthi** [comment]
Thx
