### ISSUE TITLE
"export 'Url' was not found in './Url.vue'

### ISSUE THREAD

**Issue by mauthi** [enso-ui/users#4]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

I get the following warning on building:
<img width="811" alt="image" src="https://user-images.githubusercontent.com/7204559/155848406-c99aabeb-9384-446b-ba3d-ad4c573935b8.png">

### Steps to Reproduce

1. run `yarn serve`

### Expected behavior

No warning

### Actual behavior

Warning

**Comment by robbykrlos** [comment]
@mauthi - it may be related to this https://github.com/laravel-enso/enso/issues/418. Warning is fixed in a future release (v6.0) but not yet public.

**Comment by mauthi** [comment]
I upgraded to 5.0.0 and issue seems to be fixed. Will close this now.

**Comment by robbykrlos** [comment]
@mauthi were you forced to upgrade PHP to 8.1 while upgrading to 5.0.0?
